### ISSUE TITLE
Index Out of bounds when loading occasionally

### ISSUE THREAD

**Issue by Felys1998** [goaaats/Dalamud.FindAnything#21]
```
2022-04-18 14:27:32.228 -07:00 [ERR] [LOCALPLUGIN] Error while loading Wotsit
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Lumina.Excel.ExcelSheet`1.GetEnumerator()+MoveNext()
   at Dalamud.FindAnything.TextureCache..ctor(UiBuilder uiBuilder, DataManager data) in C:\goatsoft\smile\TextureCache.cs:line 51
   at Dalamud.FindAnything.FindAnythingPlugin..ctor() in C:\goatsoft\smile\FindAnythingPlugin.cs:line 1228
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.Create(Type objectType, Object[] scopedObjects)
   at Dalamud.Plugin.Internal.LocalPlugin.Load(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\LocalPlugin.cs:line 334
```

I cannot consistently repro this, it just seems to happen sometimes when my game loads and after a restart its perfectly happy to work again.

**Comment by goaaats** [comment]
I believe this is a Lumina bug. We're already tracking it there, may be fixed soon. Thanks!
